spring.application.name=skillswap

server.port=1213

spring.data.mongodb.uri=mongodb+srv://saurabhbante:saurabh%40123@cluster0.isrbocu.mongodb.net/skillswap?appName=Cluster0
spring.main.allow-bean-definition-overriding=true