spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${PORT}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.main.allow-bean-definition-overriding=${SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING}
cors.allowed.origins=${CORS_ALLOWED_ORIGINS}